### ISSUE TITLE
Getting Sandbox example running locally

### ISSUE THREAD

**Issue by pReya** [konsoletyper/teavm-javac#6]
Hey @konsoletyper,
sorry to bother you again, but I've never used Java in the web context, so I don't know anything about .war, Tomcat, etc. For experienced devs the readme.md is probably sufficient, but for me it leaves a couple of questions. I'm trying to get the Sandbox example editor running locally.

I compiled via `mvn package` and then deployed the .war file to Apache Tomcat using the Manager UI. However as far as I can tell the war file does not contain any UI code, correct? So how do I get the UI up and running? I've seen a couple of node modules in the UI folder, and again I'm unsure what they're for? I thought the goal was to run everything in the browser, so what's the reasoning for the node components?

Sorry for my stupid questions, I'd really like to understand the concepts behind this project.

**Comment by konsoletyper** [comment]
Where do you get `war` file? The proper location should be `ui/target/teavm-javac-ui-1.0-SNAPSHOT.war`. The content of this war file is deployed to `http://teavm.org/sandbox/`, so you should see exactly the same page when you deploy this war locally.

node.js is used to download and minify [bootstrap](https://getbootstrap.com/) and [CodeMirror](https://codemirror.net/) during build time. These libraries are used in UI.

**Comment by pReya** [comment]
According to the readme, I used the war file from `compiler/target/`. Now I've tried to use the war file in `ui/target` and deployed it to Tomcat, and now everything works perfectly. Thank you!
