### ISSUE TITLE
BuildTimeResourceProxy  emits wrong js-code

### ISSUE THREAD

**Issue by frankbauer** [konsoletyper/teavm-javac#7]
Hi.

A while back you pointed me to this very cool javac repo of yours. I have been playing around with it for some time and successfully extended some of its functionality for my usecase. I also started to upgrade the repo to the latest jdk and teaVM version. Building my fork(https://github.com/frankbauer/teavm-javac/tree/custom-fielname) seems to work without any error messages using `mvn package`.

However, when I try the example, the following error is reported:

> ReferenceError: Can't find variable: T$p

If I read the code correctly, this error is created in the _classes.js_ file in the following code:
`"BuildTimeResourceProxy",117,B,[T$p],0,0,0,0,Z$h,"BuildTimeResourceProxyFactory"` 

I assume that this _Type_ is the class that [`BuildTimeResourceProxy`](https://github.com/konsoletyper/teavm/blob/243901ec106b47399f1b88187ff2ed9e0c0b54d8/platform/src/main/java/org/teavm/platform/plugin/BuildTimeResourceProxy.java) inherits from  (java.lang.reflect.InvocationHandler).

Since I am still very new to TeaVM I do not know what part of the build process (generating the classlib.txt or calling the TeaVM compiler that creates the classes.js) I have to change to make this a known type. Could you maybe point me in the right direct?

**Comment by konsoletyper** [comment]
I updated this project to the latest version of TeaVM and fixed all corresponding issues

**Comment by frankbauer** [comment]
Thanks, that did the trick.
